// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC5tajfTydqagInH2C0gU-G7biosZjQdA',
    appId: '1:12621387638:web:cb0dd266d12e817344cc57',
    messagingSenderId: '12621387638',
    projectId: 'material-store-7d076',
    authDomain: 'material-store-7d076.firebaseapp.com',
    storageBucket: 'material-store-7d076.firebasestorage.app',
    measurementId: 'G-G4LFSWNS21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRfX9ONx5XJwUBnOiVoU6SVdAEghydS7c',
    appId: '1:12621387638:android:106753e5dce7583944cc57',
    messagingSenderId: '12621387638',
    projectId: 'material-store-7d076',
    storageBucket: 'material-store-7d076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_l-fXLe7RY1isJK_LWney3I320uffGs',
    appId: '1:12621387638:ios:1f2abfeaaab0333244cc57',
    messagingSenderId: '12621387638',
    projectId: 'material-store-7d076',
    storageBucket: 'material-store-7d076.firebasestorage.app',
    iosBundleId: 'com.example.materialStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_l-fXLe7RY1isJK_LWney3I320uffGs',
    appId: '1:12621387638:ios:1f2abfeaaab0333244cc57',
    messagingSenderId: '12621387638',
    projectId: 'material-store-7d076',
    storageBucket: 'material-store-7d076.firebasestorage.app',
    iosBundleId: 'com.example.materialStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC5tajfTydqagInH2C0gU-G7biosZjQdA',
    appId: '1:12621387638:web:a03415454861cf7344cc57',
    messagingSenderId: '12621387638',
    projectId: 'material-store-7d076',
    authDomain: 'material-store-7d076.firebaseapp.com',
    storageBucket: 'material-store-7d076.firebasestorage.app',
    measurementId: 'G-NG18S45XX6',
  );
}
